
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2p-devops-test-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akatruk/p2p-devops-test
    path: devops
    targetRevision: staging
    helm:
      valueFiles: 
        - values-stg.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: p2p-devops-test-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    automated:
      prune: true
      selfHeal: true
      