apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2p-devops-test
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: 2p2-devops-test-production
  source:
    path: .helm
    repoURL: https://github.com/akatruk/p2p-devops-test.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      valueFiles:
      - .helm/values-prod.yaml
      - .helm/values-stg.yaml