apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.containers.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        resources:
          limits: {{ .Values.app.limits | toYaml | nindent 12 }}
          requests: {{ .Values.app.requests | toYaml | nindent 12 }}