apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2p-devops-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akatruk/p2p-devops-test.git
    targetRevision: HEAD
    path: /
    helm:
      valueFiles:
      - values-prod.yaml
      - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 2p2-devops-test-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    automated:
      prune: true
      selfHeal: true