replicaCount: 1

app:
  name: p2p-devops-test
  containers: 
    image: ghcr.io/akatruk/p2p-devops-test
    tag: latest

service:
  port: 3000

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
